#!/usr/bin/python
#
# Copyright (c) 2007-2008 rPath, Inc.
#

import sys
from amiconfig import AMIConfig

if len(sys.argv) == 2 and sys.argv[1] == '--debug':
    debug = True
    try:
        from conary.lib import util
        sys.excepthook = util.genExcepthook()
    except ImportError:
        pass
else:
    debug = False

amiConfig = AMIConfig(debug=debug)
sys.exit(amiConfig.configure())
