#!/usr/bin/python
#
# Copyright (c) 2007-2011 rPath, Inc.
#

import sys
from optparse import OptionParser, Option

optionsTable = [
    Option('--debug', action="store_true",
        help="Run in debugging mode"),
    Option('--probe', action="store_true",
        help="Probe if the metadata service is available"),
]
optparser = OptionParser(option_list=optionsTable)
options, args = optparser.parse_args()

if options.probe:
    try:
        from amiconfig import metadataservice
    except ImportError, e:
        sys.stderr.write("Unable to import amiconfig module: %s\n" % (e, ))
        sys.exit(10)
    canConnect = metadataservice.MetadataService.canConnect()
    messages = [ "not found", "found" ]
    sys.stderr.write("Metadata service: %s\n" % messages[canConnect])
    sys.exit(not canConnect)

from amiconfig import AMIConfig

try:
    from conary.lib import util
    sys.excepthook = util.genExcepthook(debug=options.debug)
except ImportError:
    pass

from amiconfig.lib import log
from conary.lib import log as clog
clog.setVerbosity(clog.DEBUG)
clog.syslog = log.info
clog.debug = log.info

amiConfig = AMIConfig(debug=options.debug)
sys.exit(amiConfig.configure())
